export const UPDATE_FILTER = "UPDATE_FILTER";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
//cart type
export const LOAD_CART = "LOAD_CART";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const CHANGE_PRODUCT_QUANTITY = "CHANGE_PRODUCT_QUANTITY";
export const UPDATE_CART = "UPDATE_CART";

export const UPDATE_SORT = "UPDATE_SORT";

export const LOAD_PRODUCT = "LOAD_PRODUCT";

//User Type
// export const REGISTER_REQUEST = 'USERS_REGISTER_REQUEST';
// export const REGISTER_SUCCESS = 'USERS_REGISTER_SUCCESS';
// export const REGISTER_FAILURE = 'USERS_REGISTER_FAILURE';
// export const LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';
// export const LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
// export const LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';
// export const LOGOUT = 'USERS_LOGOUT';
// export const GETALL_REQUEST = 'USERS_GETALL_REQUEST';
// export const GETALL_SUCCESS = 'USERS_GETALL_SUCCESS';
// export const GETALL_FAILURE = 'USERS_GETALL_FAILURE';
// export const DELETE_REQUEST = 'USERS_DELETE_REQUEST';
// export const DELETE_SUCCESS = 'USERS_DELETE_SUCCESS';
// export const DELETE_FAILURE = 'USERS_DELETE_FAILURE';

export const userConstants = {
  REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
  REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
  REGISTER_FAILURE: "USERS_REGISTER_FAILURE",

  LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USERS_LOGIN_FAILURE",

  LOGOUT: "USERS_LOGOUT",

  GETALL_REQUEST: "USERS_GETALL_REQUEST",
  GETALL_SUCCESS: "USERS_GETALL_SUCCESS",
  GETALL_FAILURE: "USERS_GETALL_FAILURE",

  DELETE_REQUEST: "USERS_DELETE_REQUEST",
  DELETE_SUCCESS: "USERS_DELETE_SUCCESS",
  DELETE_FAILURE: "USERS_DELETE_FAILURE",
};
